export const Easy = [
    "Ron Forbes helped her to continue with music. He spotted her potential and said, “Don’t listen through your ears, try to sense it some other way.” He began by tuning two large drums to different notes.",
    "The Eiffel Tower was initially built as a temporary exhibit for the 1889 World's Fair, but it became a permanent landmark due to its popularity, standing at 1,063 feet (324 meters) tall.",
    "The Colosseum in Rome, Italy, once held up to 80,000 spectators and hosted gladiator fights and public spectacles, serving as an iconic symbol of the Roman Empire.",
    "Giraffes have impressively long necks with only seven vertebrae, like humans. Their unique blood pressure regulation enables them to bend down and drink water safely.",
    "The Great Barrier Reef off Australia's coast is the world's largest coral reef, spanning 1,400 miles. It teems with diverse marine life and attracts divers worldwide.",
]

export const Medium = [
    "The teacher of today is the salt of the earth. He wants to create a man, not just make money. He is a knowledgeable gentleman. He is an expert in the particular subject he teaches. Though a scholar, he teaches the subject in such a way that all students, brilliant or ordinary, can fully understand him. He doesn’t advertise his knowledge.",
    "Gardening is my favourite hobby. I own a small plot of land next to our house. I cultivate gardening there. Every day, I spend half an hour gardening. After returning from my morning walk, I go to my garden with a spade and a bucket of water. I prepare the soil, prune the plants, and water them. I feel heavenly pleasure as I watch them grow day by day.",
    "The human brain, a marvel of nature, consists of approximately 100 billion neurons, each forming intricate connections and networks. This astonishing organ empowers us to think, reason, learn, and experience emotions, making us the most intelligent species on the planet.",
    "Home is the place where we return to rest after a day’s work, and where parents and children meet together and have a carefree and joyful time. Our family consists of three members—father, mother, and brother. We live in a rural area. It is free from the hustle and bustle of city life. It is especially famous for its scenic beauty.",
    "The basic technique stands in contrast to hunt and peck typing in which the typist keeps his or her eyes on the source copy at all times. Touch typing also involves the use of the home row method, where typists keep their wrists up, rather than resting them on a desk or keyboard (which can cause carpal tunnel syndrome). To avoid this, typists should sit up tall, leaning slightly forward from the waist, place their feet flat on the floor in front of them with one foot slightly in front of the other, and keep their elbows close to their sides with forearms slanted slightly upward to the keyboard; fingers should be curved slightly and rest on the home row.",
]

export const Hard = [
    "The Great Wall of China is one of the most remarkable engineering feats in history, stretching over 13,000 miles (21,196 kilometers) across China's northern borders. Contrary to popular belief, it cannot be seen from space with the naked eye. The Wall's construction took centuries, with the first sections built as early as the 7th century BC, primarily to protect against invasions from the north. Throughout its existence, the Wall was expanded, rebuilt, and modified by various dynasties. Today, it stands as a symbol of China's rich cultural heritage and a testament to human ingenuity and perseverance.",
    "Time is more precious than money is. Once the money is used, it can be earned again, but the time which has passed will never return. We all must have heard the famous proverb, ‘Time and Tide wait for none.’ Time never waits for anyone or anything. In fact, we have to wait for the perfect time. There is a perfect time for everything; therefore, think about how precious it is, and utilise it ideally before time fails. People say money can buy everything, but money can never buy time for you. So, understand the value of time and use it wisely.",
    "The Amazon Rainforest, located in South America, is the largest tropical rainforest on Earth. Covering approximately 2.1 million square miles (5.5 million square kilometers), it spans across nine countries and contains a staggering diversity of plant and animal species. Scientists estimate that about 400 billion individual trees belonging to 16,000 different species thrive in this biodiversity hotspot. The Amazon Rainforest plays a vital role in stabilizing the global climate, acting as a carbon sink and producing a significant portion of the world's oxygen. Sadly, it faces severe threats from deforestation, which poses significant risks to the planet's ecological balance.",
    "The blue whale, known as the largest animal on Earth, can reach lengths of up to 100 feet (30 meters) and weigh over 200 tons. Despite its immense size, its primary diet consists of tiny shrimp-like animals called krill, which it consumes in massive quantities during feeding seasons. Blue whales are known for their hauntingly beautiful songs that can travel thousands of miles underwater.",
    "Mount Everest, the highest peak in the world, rises to a staggering height of 29,032 feet (8,848 meters) above sea level. Climbing this legendary mountain is an extreme challenge, and the summit's thin air can make it treacherous for climbers. As of now, over 4,000 people have reached its summit, and unfortunately, many have lost their lives during the attempt. Mount Everest is part of the majestic Himalayas, which stretch across several countries, and the region is rich in cultural diversity, with unique traditions and customs. It remains a destination of allure for mountaineers and adventurers from around the globe.",
]

